#print("Sum:", int(input("Enter number one\n")) + int(input("Enter number two\n")))               
#numberOne = input("Enter your first number to get a sum\n")
#numberTwo = input("Enter your second number to get a sum\n")
#print("Sum:", numberOne, "+", numberTwo, "=", int(numberOne) + int(numberTwo))
numberOne, numberTwo =input('Enter two nubmers and get sum\n').split()
print (numberOne, "+" ,numberTwo , "=", int(numberOne)+int(numberTwo))
